-- MySQL Script generated by MySQL Workbench
-- Wed Nov  2 21:22:07 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BlogManagementSystemDB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Users` ;

CREATE TABLE IF NOT EXISTS `Users` (
  `user_id` INT NOT NULL,
  `first_name` VARCHAR(65) NOT NULL,
  `last_name` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Account` ;

CREATE TABLE IF NOT EXISTS `Account` (
  `account_id` INT(15) NOT NULL,
  `username` VARCHAR(65) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `user_id` INT(15) NOT NULL,
  PRIMARY KEY (`account_id`, `user_id`),
  INDEX `ACCOUNT_USER_FK_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `ACCOUNT_USER_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `multimedia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `multimedia` ;

CREATE TABLE IF NOT EXISTS `multimedia` (
  `multimedia_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `lifetime` INT NOT NULL,
  PRIMARY KEY (`multimedia_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `music`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `music` ;

CREATE TABLE IF NOT EXISTS `music` (
  `music_id` INT NOT NULL,
  `title` VARCHAR(65) NOT NULL,
  `type` VARCHAR(25) NOT NULL,
  `description` VARCHAR(250) NOT NULL,
  `multimedia_id` INT NOT NULL,
  PRIMARY KEY (`music_id`, `multimedia_id`),
  INDEX `MUSIC_MULTI_FK_idx` (`multimedia_id` ASC) VISIBLE,
  CONSTRAINT `MUSIC_MULTI_FK`
    FOREIGN KEY (`multimedia_id`)
    REFERENCES `multimedia` (`multimedia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Searches`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Searches` ;

CREATE TABLE IF NOT EXISTS `Searches` (
  `searches_id` INT NOT NULL,
  `searches_count` INT NOT NULL,
  `type` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`searches_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Tag`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Tag` ;

CREATE TABLE IF NOT EXISTS `Tag` (
  `tag_id` INT NOT NULL,
  `tag_count` INT NOT NULL,
  `type` VARCHAR(65) NOT NULL,
  `searches_id` INT NOT NULL,
  PRIMARY KEY (`tag_id`, `searches_id`),
  INDEX `TAG_SRCH_FK_idx` (`searches_id` ASC) VISIBLE,
  CONSTRAINT `TAG_SRCH_FK`
    FOREIGN KEY (`searches_id`)
    REFERENCES `Searches` (`searches_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Upgraded Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Upgraded Account` ;

CREATE TABLE IF NOT EXISTS `Upgraded Account` (
  `upgraded_account_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`upgraded_account_id`, `account_id`),
  INDEX `UPGRD_ACC_FK_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `UPGRD_ACC_FK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Upvote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Upvote` ;

CREATE TABLE IF NOT EXISTS `Upvote` (
  `upvote_id` INT NOT NULL,
  `upvote_count` INT NOT NULL,
  `upvote_type` VARCHAR(65) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`upvote_id`, `user_id`),
  INDEX `UPVOTE_USR_FK_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `UPVOTE_USR_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Video`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Video` ;

CREATE TABLE IF NOT EXISTS `Video` (
  `video_id` INT NOT NULL,
  `title` VARCHAR(65) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `type` VARCHAR(15) NOT NULL,
  `multimedia_id` INT NOT NULL,
  PRIMARY KEY (`video_id`, `multimedia_id`),
  INDEX `VIDEO_MULTI_FK_idx` (`multimedia_id` ASC) VISIBLE,
  CONSTRAINT `VIDEO_MULTI_FK`
    FOREIGN KEY (`multimedia_id`)
    REFERENCES `multimedia` (`multimedia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Product` ;

CREATE TABLE IF NOT EXISTS `Product` (
  `product_id` INT NOT NULL,
  `creation_date` DATE NOT NULL,
  `name` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`product_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `devices`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `devices` ;

CREATE TABLE IF NOT EXISTS `devices` (
  `devices_id` INT NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  `lifetime` INT NOT NULL,
  PRIMARY KEY (`devices_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Runs On`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Runs On` ;

CREATE TABLE IF NOT EXISTS `Runs On` (
  `runs_on_id` INT NOT NULL,
  `products_id` INT NOT NULL,
  `devices_id` INT NOT NULL,
  PRIMARY KEY (`runs_on_id`),
  INDEX `PROD_RUNON_FK_idx` (`products_id` ASC) VISIBLE,
  INDEX `DEV_RUNON_FK_idx` (`devices_id` ASC) VISIBLE,
  CONSTRAINT `PROD_RUNON_FK`
    FOREIGN KEY (`products_id`)
    REFERENCES `Product` (`product_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `DEV_RUNON_FK`
    FOREIGN KEY (`devices_id`)
    REFERENCES `devices` (`devices_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `admin` ;

CREATE TABLE IF NOT EXISTS `admin` (
  `admin_id` INT NOT NULL,
  `rank` INT NOT NULL,
  `name` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `advertisements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `advertisements` ;

CREATE TABLE IF NOT EXISTS `advertisements` (
  `advertisement_id` INT NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `body` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`advertisement_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `articles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `articles` ;

CREATE TABLE IF NOT EXISTS `articles` (
  `article_id` INT NOT NULL,
  `title` VARCHAR(150) NOT NULL,
  `body` VARCHAR(300) NOT NULL,
  PRIMARY KEY (`article_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Monitors`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Monitors` ;

CREATE TABLE IF NOT EXISTS `Monitors` (
  `monitors_id` INT NOT NULL,
  `admin_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  `multimedia_id` INT NOT NULL,
  `advertisement_id` INT NOT NULL,
  `article_id` INT NOT NULL,
  PRIMARY KEY (`monitors_id`),
  INDEX `ADMIN_MON_FK_idx` (`admin_id` ASC) VISIBLE,
  INDEX `MON_ACC_FK_idx` (`account_id` ASC) VISIBLE,
  INDEX `MON_MULTI_FK_idx` (`multimedia_id` ASC) VISIBLE,
  INDEX `MON_ART_FK_idx` (`article_id` ASC) VISIBLE,
  INDEX `MON_AD_FK_idx` (`advertisement_id` ASC) VISIBLE,
  CONSTRAINT `ADMIN_MON_FK`
    FOREIGN KEY (`admin_id`)
    REFERENCES `admin` (`admin_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MON_ACC_FK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MON_MULTI_FK`
    FOREIGN KEY (`multimedia_id`)
    REFERENCES `multimedia` (`multimedia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MON_AD_FK`
    FOREIGN KEY (`advertisement_id`)
    REFERENCES `advertisements` (`advertisement_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `MON_ART_FK`
    FOREIGN KEY (`article_id`)
    REFERENCES `articles` (`article_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `blog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `blog` ;

CREATE TABLE IF NOT EXISTS `blog` (
  `blog_id` INT NOT NULL,
  `date_created` DATE NOT NULL,
  `title` VARCHAR(65) NOT NULL,
  PRIMARY KEY (`blog_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `category` ;

CREATE TABLE IF NOT EXISTS `category` (
  `category_id` INT NOT NULL,
  `category_count` INT(50) NOT NULL,
  `type` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Report`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Report` ;

CREATE TABLE IF NOT EXISTS `Report` (
  `report_id` INT NOT NULL,
  `title` VARCHAR(65) NOT NULL,
  `body` VARCHAR(150) NOT NULL,
  `date_created` DATE NOT NULL,
  PRIMARY KEY (`report_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Contains`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Contains` ;

CREATE TABLE IF NOT EXISTS `Contains` (
  `contains_id` INT NOT NULL,
  `blog_id` INT NOT NULL,
  `tag_id` INT NOT NULL,
  `searches_id` INT NOT NULL,
  `category_id` INT NOT NULL,
  `report_id` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`contains_id`, `blog_id`),
  INDEX `CNTNS_BLOG_FK_idx` (`blog_id` ASC) VISIBLE,
  INDEX `CNTNS_SRCS_FK_idx` (`searches_id` ASC) VISIBLE,
  INDEX `CNTNS_TAG_FK_idx` (`tag_id` ASC) VISIBLE,
  INDEX `CNTNS_CAT_FK_idx` (`category_id` ASC) VISIBLE,
  INDEX `CNTNS_REP_FK_idx` (`report_id` ASC) VISIBLE,
  INDEX `CNTNS_ACC_FK_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `CNTNS_BLOG_FK`
    FOREIGN KEY (`blog_id`)
    REFERENCES `blog` (`blog_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CNTNS_SRCS_FK`
    FOREIGN KEY (`searches_id`)
    REFERENCES `Searches` (`searches_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CNTNS_TAG_FK`
    FOREIGN KEY (`tag_id`)
    REFERENCES `Tag` (`tag_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CNTNS_CAT_FK`
    FOREIGN KEY (`category_id`)
    REFERENCES `category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CNTNS_REP_FK`
    FOREIGN KEY (`report_id`)
    REFERENCES `Report` (`report_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `CNTNS_ACC_FK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `comment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `comment` ;

CREATE TABLE IF NOT EXISTS `comment` (
  `comment_id` INT NOT NULL,
  `date_created` VARCHAR(45) NOT NULL,
  `body` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`comment_id`, `user_id`),
  INDEX `COMMENT_USR_FK_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `COMMENT_USR_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `company` ;

CREATE TABLE IF NOT EXISTS `company` (
  `company_id` INT NOT NULL,
  `company_name` VARCHAR(150) NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`company_id`, `account_id`),
  INDEX `COMPANY_ACC_FK_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `COMPANY_ACC_FK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `digital_image`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `digital_image` ;

CREATE TABLE IF NOT EXISTS `digital_image` (
  `digital_image_id` INT NOT NULL,
  `title` VARCHAR(65) NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `type` VARCHAR(25) NOT NULL,
  `multimedia_id` INT NOT NULL,
  PRIMARY KEY (`digital_image_id`, `multimedia_id`),
  INDEX `DIGIMG_MULTI_FK_idx` (`multimedia_id` ASC) VISIBLE,
  CONSTRAINT `DIGIMG_MULTI_FK`
    FOREIGN KEY (`multimedia_id`)
    REFERENCES `multimedia` (`multimedia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Limited Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Limited Account` ;

CREATE TABLE IF NOT EXISTS `Limited Account` (
  `limited_account_id` INT NOT NULL,
  `limited_account_period` INT NOT NULL,
  `subscription_duration` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`limited_account_id`, `account_id`),
  INDEX `LIM_ACCOUNT_FK_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `LIM_ACCOUNT_FK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `photo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `photo` ;

CREATE TABLE IF NOT EXISTS `photo` (
  `photo_id` INT NOT NULL,
  `description` VARCHAR(150) NOT NULL,
  `title` VARCHAR(65) NOT NULL,
  `type` VARCHAR(25) NOT NULL,
  `multimedia_id` INT NOT NULL,
  PRIMARY KEY (`photo_id`, `multimedia_id`),
  INDEX `PHOTO_MULTI_FK_idx` (`multimedia_id` ASC) VISIBLE,
  CONSTRAINT `PHOTO_MULTI_FK`
    FOREIGN KEY (`multimedia_id`)
    REFERENCES `multimedia` (`multimedia_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `post` ;

CREATE TABLE IF NOT EXISTS `post` (
  `post_id` INT NOT NULL,
  `title` VARCHAR(65) NOT NULL,
  `body` VARCHAR(150) NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`post_id`, `category_id`),
  INDEX `POST_CAT_FK_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `POST_CAT_FK`
    FOREIGN KEY (`category_id`)
    REFERENCES `category` (`category_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Prime Account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Prime Account` ;

CREATE TABLE IF NOT EXISTS `Prime Account` (
  `prime_account_id` INT NOT NULL,
  `prime_account_period` INT NOT NULL,
  `subscription_duration` INT NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`prime_account_id`, `account_id`),
  INDEX `PRIME_ACC_FK_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `PRIME_ACC_FK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `privileges`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `privileges` ;

CREATE TABLE IF NOT EXISTS `privileges` (
  `privileges_id` INT NOT NULL,
  `rank` INT NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`privileges_id`, `user_id`),
  INDEX `PRIV_FK_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `PRIV_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Registered User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Registered User` ;

CREATE TABLE IF NOT EXISTS `Registered User` (
  `registered_user_id` INT NOT NULL,
  `name` VARCHAR(65) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`registered_user_id`, `user_id`),
  INDEX `REG_USER_FK_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `REG_USER_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Roles` ;

CREATE TABLE IF NOT EXISTS `Roles` (
  `roles_id` INT NOT NULL,
  `conditon` VARCHAR(45) NOT NULL,
  `theme` VARCHAR(45) NOT NULL,
  `account_id` INT NOT NULL,
  PRIMARY KEY (`roles_id`, `account_id`),
  INDEX `ROLES_ACC_FK_idx` (`account_id` ASC) VISIBLE,
  CONSTRAINT `ROLES_ACC_FK`
    FOREIGN KEY (`account_id`)
    REFERENCES `Account` (`account_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Unregistered User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Unregistered User` ;

CREATE TABLE IF NOT EXISTS `Unregistered User` (
  `unregistered_user_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`unregistered_user_id`, `user_id`),
  INDEX `UNREG_USR_FK_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `UNREG_USR_FK`
    FOREIGN KEY (`user_id`)
    REFERENCES `Users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
